// Package leaf handles the mapping between store targets and the concrete
// dotfiles on disk, plus dotenv parsing/serialization.
//
// Filename convention (derived from a target's basepath directory + env +
// tier):
//
//	tier=buildtime -> <dir>/.env[.<env>]        (read by the build; NEXT_PUBLIC_*, etc.)
//	tier=runtime   -> <dir>/.dev.vars[.<env>]   (read by wrangler locally; pushed as secrets)
//
// The sentinel env "_" (store.DefaultEnv) produces suffix-less files: .env and
// .dev.vars.
package leaf

import (
	"bufio"
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/taigrr/gitward/internal/store"
)

// FileName returns the dotfile name (no directory) for a tier+env.
func FileName(tier store.Tier, env string) string {
	base := ".env"
	if tier == store.Runtime {
		base = ".dev.vars"
	}
	if env == store.DefaultEnv || env == "" {
		return base
	}
	return base + "." + env
}

// Path returns the full path (dir joined with the derived filename) for a
// target basepath, tier, and env.
func Path(basepath string, tier store.Tier, env string) string {
	return filepath.Join(basepath, FileName(tier, env))
}

// Parse reads dotenv content into a flat map. It ignores blank lines and
// comment lines (leading '#'); the store is the source of truth for structure,
// so comments live only in *.example files and are intentionally dropped here.
// Surrounding single or double quotes on values are stripped. A leading
// "export " is tolerated.
func Parse(content string) (map[string]string, error) {
	out := map[string]string{}
	sc := bufio.NewScanner(strings.NewReader(content))
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	ln := 0
	for sc.Scan() {
		ln++
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		line = strings.TrimPrefix(line, "export ")
		eq := strings.IndexByte(line, '=')
		if eq < 0 {
			return nil, fmt.Errorf("line %d: missing '=' in %q", ln, line)
		}
		key := strings.TrimSpace(line[:eq])
		if key == "" {
			return nil, fmt.Errorf("line %d: empty key", ln)
		}
		val := strings.TrimSpace(line[eq+1:])
		val = unquote(val)
		out[key] = val
	}
	if err := sc.Err(); err != nil {
		return nil, err
	}
	return out, nil
}

func unquote(s string) string {
	if len(s) >= 2 {
		if (s[0] == '"' && s[len(s)-1] == '"') || (s[0] == '\'' && s[len(s)-1] == '\'') {
			return s[1 : len(s)-1]
		}
	}
	return s
}

// IgnoredHeader introduces the trailing block of ward-ignored variables in a
// generated leaf file. Variables below it are preserved (their parsed values
// re-serialized) and never captured into the store.
const IgnoredHeader = "# ward-ignored variables below"

// Serialize renders a flat map into deterministic dotenv content (keys sorted),
// quoting values that contain whitespace or characters that would otherwise be
// ambiguous. A generated-file header warns humans not to edit blindly.
func Serialize(vals map[string]string) string {
	return SerializeWithIgnored(vals, nil)
}

// SerializeWithIgnored renders the managed values followed by an ignored block.
// The ignored block (introduced by IgnoredHeader) is only emitted when there is
// at least one ignored variable to preserve, so files with no ignored variables
// look exactly as before.
func SerializeWithIgnored(vals, ignored map[string]string) string {
	var b strings.Builder
	b.WriteString("# Generated by ward (gitward). Edits are captured on commit.\n")
	writeSorted(&b, vals)
	if len(ignored) > 0 {
		b.WriteString(IgnoredHeader)
		b.WriteByte('\n')
		writeSorted(&b, ignored)
	}
	return b.String()
}

func writeSorted(b *strings.Builder, vals map[string]string) {
	keys := make([]string, 0, len(vals))
	for k := range vals {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		b.WriteString(k)
		b.WriteByte('=')
		b.WriteString(quote(vals[k]))
		b.WriteByte('\n')
	}
}

func quote(v string) string {
	if v == "" {
		return v
	}
	if strings.ContainsAny(v, " \t\"'#\n") {
		return `"` + strings.ReplaceAll(v, `"`, `\"`) + `"`
	}
	return v
}
